// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7GaR-FX7P2V8qezEaNANHO9_wFrQP-Sw',
    appId: '1:24700300548:web:5c49a7138a1cdc1ac33451',
    messagingSenderId: '24700300548',
    projectId: 'veerav-app',
    authDomain: 'veerav-app.firebaseapp.com',
    storageBucket: 'veerav-app.appspot.com',
    measurementId: 'G-44545133LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8EUEuECh7nkaxpcTIWY8Kf0aE74uvNTU',
    appId: '1:24700300548:android:8309f44953b28f3cc33451',
    messagingSenderId: '24700300548',
    projectId: 'veerav-app',
    storageBucket: 'veerav-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT7kv_El8jEMaQqy2zVcR_qkEZfUsgd4Q',
    appId: '1:24700300548:ios:2c8eebd847e45fa6c33451',
    messagingSenderId: '24700300548',
    projectId: 'veerav-app',
    storageBucket: 'veerav-app.appspot.com',
    iosBundleId: 'com.example.swooshedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT7kv_El8jEMaQqy2zVcR_qkEZfUsgd4Q',
    appId: '1:24700300548:ios:2c2a46e24f8978ccc33451',
    messagingSenderId: '24700300548',
    projectId: 'veerav-app',
    storageBucket: 'veerav-app.appspot.com',
    iosBundleId: 'com.example.swooshedApp.RunnerTests',
  );
}
